### PR TITLE
Enable change-of-email confirmation for users

### PR DESCRIPTION
**Pull request by reefdog**
This PR enables email confirmation for users changing their email address. This is a necessary prerequisite for cleanly converting applicants (which require confirmed emails) to users, and is good form besides.

**Testing:**
- Start Rails and Sidekiq
- Log in and go to your user settings screen (http://localhost:3000/account)
- Update your email address to a new one (that you actually have access to)
- ✅ See a flash that tells you to go check your email
- ✅ Verify (in console/database) that your email has not _actually_ changed yet
- Go check your email! Click the confirmation link inside. (Ignore the email design and language. This is Devise boilerplate that we will customize.)
- ✅ Clicking the link should confirm the email change; verify in console/database

Issue #271

### CODE REVIEW

**Comment by cguess** [comment]
The Update Account Details page is failing on Safari. Specifically the text boxes are too small to actually see the text you're typing and the input box "jumps" around after the first input (see screenshots below). Specifically:
- Open page
- Click on "change email" input box
- type something (the hint text will disappear, but no more text will show up)
- click on the form outside the box, the box will jump lower

Screen Shot 2022-09-13 at 9 04 53 AM

I'm going to finish up the rest of the testing on Firefox, but this should be addressed since I'd bet it'll break on iOS and iPadOS as well.

**Review by cguess — CHANGES_REQUESTED** [review]
This all works great except on Safari (the text box is just too small I'd guess). Otherwise it's good to go.

**Comment by reefdog** [comment]
@cguess This PR doesn't change the user settings screens, just the back-end logic upon entering a new email. (Before, the change happened immediately; now, it requires confirmation.)

I'll be redoing the settings screens entirely in #298, can I copy your notes over to that issue and skip them for this PR?

**Comment by cguess** [comment]
Yep go ahead!

**Pull request merged**
