### PR TITLE
Let new users complete their account setup

### LINKED ISSUE #271: Build applicant → user pipeline
_This task is part of #296 and follows the design of #268._

Once applicants have confirmed their email address, we need to be able to approve or reject them, along with a reason. This approval/rejection should be communicated back to the applicant. If approved, they should be converted to a proper user, but forced to choose a password upon following the welcome link.

This issue is for that functionality, but the actual admin approval/rejection will be triggered by a Rails console method. (The UI in the site itself will be done in a future task.)

- [x] Approve/reject applications (with reasons)
- [x] Create users from approved applicants
- [x] Allow users to choose password

### PR DESCRIPTION
**Pull request by reefdog**
This PR adds the final piece to #271: letting newly-approved users receive an email with their setup instructions, with a link to choose a password and come on in. As with the previous PRs in this chain, testing it is a little bit clunky until we complete #273.

🚨 Note that this PR now includes some new database seeds, so you may want to re-seed. (You don't have to, though; read the prerequisites block. However, future PRs will likely assume you have re-seeded and will make use of these seeds.)

**Testing prerequisite:**

To test this, you need a **newly-created applicant** that has **confirmed their email address** and been **approved by an admin**, and then been **turned into a user**. You can either go through that process manually:

1. Go to http://localhost:3000/apply and apply for a new account (with an email address you control)
2. Check your email, click the link, confirm their email address
3. Switch to the Rails console: `rails c`
4. Find that applicant (`a = Applicant.find(…)`) and approve them: `a.approve`
5. Create a user from that now-approved applicant: `u = User.create_from_applicant(a)`

Or you can re-seed your database to pick up some new seeds, which shaves some steps off. You still have to start with an applicant, so you can update it to have an email address you can receive email at before creating the user:

```ruby
a = Applicant.find_by(email: "approved-applicant@example.com")
a.update!(email: "some-email@you-can-access")
u = User.create_from_applicant(a)
```

Whichever path you choose, you can now continue on below.

**Testing:**
1. Start Rails and Sidekiq
2. Send setup instructions to that user: `u.send_setup_instructions`
3. Check your email, click the link, and choose your password
4. ✅ You should be logged in!

**Testing failing cases:**
- Try bad passwords
- Try to setup an account a second time

Closes #271

### CODE REVIEW

**Comment by cguess** [comment]
Can we add a User to `seeds.rb` that takes care of the prerequisite steps? We could also just add a bit of code that runs through the steps when we run `rails db:seed`. It seems as if that's going to be important to have hanging around from here on out for all testing purposes.

**Comment by reefdog** [comment]
> Can we add a User to seeds.rb that takes care of the prerequisite steps?

🤦 Of course! Great idea. On it.

**Comment by reefdog** [comment]
@cguess Okay, I have updated the seeds file with a whole host of new applicant and user states. The three old users remain, but now we can target each stage of the process.

So for the purposes of this PR, you could skip the prereq section and just:

```ruby
u = User.find_by(email: "unsetup-user@example.com")
# Stop! Update the user to have an email address that you can receive at. Then, continue…
u.send_setup_instructions
```

Note that you need to update the user to have an email address where you can actually receive mail, or else you'll never get the setup link.

**Review by cguess — APPROVED** [review]
This works perfectly!

Question: should we require a bit more password protection? Maybe longer than 6 characters? Just thinking out loud

**Comment by reefdog** [comment]
> should we require a bit more password protection? Maybe longer than 6 characters?

We certainly can! Here I was just mimicking Devise's defaults. I'll open a discussion issue.

**Pull request merged**
